import { test } from 'node:test';
import assert from 'node:assert/strict';
import { chmodSync, existsSync, mkdirSync, readFileSync, realpathSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { commit, fixture, git } from '../fixtures/setup.ts';
import { dossier, issueUrl, merge } from '../fixtures/linear.ts';
import { linearTarget } from '../linear-targets.ts';
import { loadConfig } from './config.ts';
import { writeJsonFile } from './ledger.ts';
import { createLinearPlan, parseLinearPlan, type LinearPlan } from './linear-plan.ts';
import { proofCatalogue } from './linear-proof.ts';
import { LINEAR_PREFIX, type NativeCall } from './linear-session.ts';
import { tickSweep } from './local.ts';
import { takeLease } from './lease.ts';
import { POST_MERGE_DEFER_HOURS, postMergeLeaseFile, postMergeLedgerFile, postMergeStateFile, redTrunkFile, type Handled, type PostMergeLedger } from './post-merge.ts';

type F = ReturnType<typeof fixture>;
const isolated = { GIT_CONFIG_GLOBAL: '/dev/null', GIT_CONFIG_NOSYSTEM: '1' };
const merged = (number: number) => ({ number, merged_at: '2026-09-29T21:35:41Z', base: { ref: 'main' } });
function edit(f: F, change: (live: ReturnType<F['read']>) => void) { const live = f.read(); change(live); Object.assign(f.state, live); f.save(); }
/** A trunk of `count` real commits on a bare origin that the primary checkout knows only as a remote, so a pass must fetch each commit it runs. The fake GitHub's tip is the first commit, and every commit's push Tests are green. */
function trunk(f: F, count: number, postMerge: Record<string, unknown> = { runs: [{ name: 'release', command: 'fake-release' }] }) {
  const origin = join(f.directory, 'origin.git');
  const work = join(f.directory, 'work');
  mkdirSync(work);
  git(f.directory, ['init', '-q', '--bare', origin]);
  git(work, ['init', '-q', '-b', 'main']);
  const commits = Array.from({ length: count }, (_, i) => { writeFileSync(join(work, 'n.txt'), String(i)); return commit(work, `trunk ${i}`); });
  git(work, ['push', '-q', origin, 'main']);
  const checkout = f.checkout();
  git(checkout, ['remote', 'add', 'origin', origin]);
  edit(f, live => {
    const config = JSON.parse(live.blobs['.cursor/converge.json']); config.postMerge = postMerge; live.blobs['.cursor/converge.json'] = JSON.stringify(config);
    live.trunkHistory = commits.map((sha, i) => ({ sha, parents: i ? [commits[i - 1]] : [] }));
    live.pushRuns = Object.fromEntries(commits.map(sha => [sha, { status: 'completed', conclusion: 'success' }]));
    live.trunk = commits[0];
  });
  const state = join(f.directory, 'state');
  const file = join(f.directory, 'converge-local.json');
  writeFileSync(file, JSON.stringify({ parent: 'claude', repos: [{ repo: 'Example/app', checkout }], pluginDir: f.directory, stateDirectory: state, sheetPath: join(f.directory, 'sheet.md'), logDirectory: f.directory }));
  // The post-merge command: it records its environment, its directory and the commit checked out there, prints a line, and exits with the code in `exits/<commit>` (0 without one), or sleeps when `sleep` exists.
  writeFileSync(join(f.directory, 'fake-release'), '#!/bin/sh\nprintf "%s|%s|%s|%s|%s|%s|%s\\n" "$PSTACK_REPO" "$PSTACK_COMMIT" "$PSTACK_PR" "$PSTACK_CHECKOUT" "$PSTACK_PLUGIN_DIR" "$(pwd -P)" "$(git rev-parse HEAD)" >> "$FAKE_DIR/released.txt"\necho "release output"\nif [ -f "$FAKE_DIR/sleep" ]; then exec sleep 30; fi\nif [ -f "$FAKE_DIR/exits/$PSTACK_COMMIT" ]; then exit "$(cat "$FAKE_DIR/exits/$PSTACK_COMMIT")"; fi\n');
  chmodSync(join(f.directory, 'fake-release'), 0o755);
  mkdirSync(join(f.directory, 'exits'));
  return { commits, checkout, file, state, stateFile: postMergeStateFile(state, 'Example/app'), ledger: (sha: string) => postMergeLedgerFile(state, 'Example/app', sha) };
}
function linearMergedPr(f: F, commitSha: string, message = `change\n\nPstack-Linear: ${issueUrl}`) {
  const d = dossier(); d.round.head = f.state.head;
  edit(f, live => {
    Object.assign(live, { merged: true, prState: 'closed', mergeCommit: commitSha, mergedAt: '2026-09-30T01:00:00Z', prCommits: [{ sha: f.state.head, commit: { message } }], commitPulls: { [commitSha]: [{ ...merged(1), merge_commit_sha: commitSha }] }, comments: [{ id: 100, body: `<!-- converge:v1 ${d.round.id} -->\n\`\`\`json\n${JSON.stringify(d)}\n\`\`\``, user: { id: 7 }, created_at: '2026-09-30T00:00:00Z', updated_at: '2026-09-30T00:00:00Z' }], statuses: [{ id: 200, context: 'verdict', state: 'success', description: 'VERIFIED by converge', creator: { id: 7 }, target_url: 'https://github.com/Example/app/pull/1#issuecomment-100' }] });
  });
}
const env = (f: F) => ({ ...isolated, FAKE_DIR: f.directory, TMPDIR: join(f.directory, 'tmp') });
const sweepTick = (f: F, file: string, extra: string[] = []) => f.run('converge-local', ['tick', '--job', 'sweep', '--config', file, ...extra], env(f));
const pass = (stdout: string) => JSON.parse(stdout).repos[0].postMerge;
const outcomes = (stdout: string) => pass(stdout).commits.map((c: Handled) => [c.commit, c.outcome, c.reason]);
const released = (f: F) => existsSync(join(f.directory, 'released.txt')) ? readFileSync(join(f.directory, 'released.txt'), 'utf8').trim().split('\n').map(line => line.split('|')) : [];
const ledgerOf = (file: string): PostMergeLedger => JSON.parse(readFileSync(file, 'utf8'));
/** tickSweep in this process, for the options the command does not take. */
async function inProcess<T>(f: F, run: () => Promise<T>): Promise<T> {
  const values: Record<string, string> = { PATH: `${f.directory}:${process.env.PATH}`, CONVERGE_FIXTURE: f.statePath, ...env(f) };
  const saved = Object.fromEntries(Object.keys(values).map(key => [key, process.env[key]]));
  Object.assign(process.env, values);
  try { return await run(); }
  finally { for (const [key, value] of Object.entries(saved)) { if (value === undefined) delete process.env[key]; else process.env[key] = value; } }
}

test('the first sweep tick with a postMerge block stores the trunk tip and runs nothing; while trunk stands still the pass reads nothing more', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, stateFile } = trunk(f, 2);
  const first = sweepTick(f, file);
  assert.equal(first.status, 0, first.stderr);
  assert.deepEqual(pass(first.stdout), { tip: commits[0], handled: commits[0], note: 'first pass: stored the trunk tip and ran nothing', commits: [], errors: [] });
  assert.deepEqual(JSON.parse(readFileSync(stateFile, 'utf8')), { schemaVersion: 1, repo: 'Example/app', tip: commits[0] });
  assert.deepEqual(released(f), []);
  const before = f.calls().length;
  const second = sweepTick(f, file);
  assert.equal(second.status, 0, second.stderr);
  assert.deepEqual(pass(second.stdout), { tip: commits[0], handled: commits[0], note: null, commits: [], errors: [] });
  assert.deepEqual(f.calls().slice(before).filter(call => /compare|commits\/[a-f0-9]{40}\/pulls|\/runs/.test(String(call[1]))), [], 'no compare, no PR lookup, no Tests read');
});
test('new trunk commits run oldest first, each in a detached worktree of its commit with the PSTACK variables, and the handled tip advances commit by commit', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, checkout, file, stateFile, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  const primary = [git(checkout, ['branch', '--list']), git(checkout, ['rev-parse', 'HEAD'])];
  edit(f, live => { live.trunk = commits[2]; live.commitPulls = { [commits[1]]: [{ ...merged(40), merged_at: null }, merged(41)] }; });
  const result = sweepTick(f, file);
  assert.equal(result.status, 0, result.stderr);
  const report = pass(result.stdout);
  assert.deepEqual(report.commits.map((c: Handled) => [c.commit, c.pr, c.outcome]), [[commits[1], 41, 'done'], [commits[2], null, 'done']]);
  assert.equal(report.handled, commits[2]);
  const lines = released(f);
  assert.deepEqual(lines.map(l => [l[0], l[1], l[2], l[3], l[4], l[6]]), [['Example/app', commits[1], '41', checkout, f.directory, commits[1]], ['Example/app', commits[2], '', checkout, f.directory, commits[2]]]);
  assert.deepEqual(lines.map(l => l[5]), report.commits.map((c: Handled) => join(realpathSync(String(c.runDirectory)), 'checkout')));
  const first = ledgerOf(ledger(commits[1]));
  assert.deepEqual([first.schemaVersion, first.repo, first.commit, first.pr, first.attempts.map(a => [a.n, a.outcome, a.reason])], [1, 'Example/app', commits[1], 41, [[1, 'done', '']]]);
  assert.deepEqual(first.attempts[0]?.runs.map(r => [r.name, r.exitCode]), [['release', 0]]);
  assert.equal(readFileSync(String(first.attempts[0]?.runs[0]?.logFile), 'utf8'), 'release output\n');
  assert.match(String(first.attempts[0]?.runDirectory), new RegExp(`/converge-local/post-merge/Example-app-${commits[1]?.slice(0, 8)}-1-\\d+$`));
  assert.equal(statSync(ledger(commits[1])).mode & 0o777, 0o600);
  assert.equal(JSON.parse(readFileSync(stateFile, 'utf8')).tip, commits[2]);
  assert.equal(git(checkout, ['worktree', 'list', '--porcelain']).match(/^worktree /gm)?.length, 1, 'every worktree is removed');
  assert.deepEqual([git(checkout, ['branch', '--list']), git(checkout, ['rev-parse', 'HEAD'])], primary, 'no branch created or moved in the primary checkout');
});
test('a commit whose push Tests have not completed, or have no run yet, waits without an error, and the commits after it wait too', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[2]; live.pushRuns[commits[1]] = { status: 'in_progress', conclusion: null }; });
  const waiting = sweepTick(f, file);
  assert.equal(waiting.status, 0, waiting.stderr);
  assert.deepEqual(pass(waiting.stdout).commits, [{ commit: commits[1], pr: null, outcome: 'waiting', reason: 'Tests has not completed on the commit', ledger: ledger(commits[1]), runDirectory: null }]);
  edit(f, live => { live.pushRuns = Object.fromEntries(Object.entries(live.pushRuns).filter(([sha]) => sha !== commits[1])); });
  const none = sweepTick(f, file);
  assert.equal(none.status, 0, none.stderr);
  assert.deepEqual(outcomes(none.stdout), [[commits[1], 'waiting', 'Tests has not completed on the commit']]);
  assert.deepEqual(released(f), []);
  assert.equal(existsSync(ledger(commits[1])), false);
  edit(f, live => { live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'success' }; });
  assert.deepEqual(outcomes(sweepTick(f, file).stdout).map((o: string[]) => o[1]), ['done', 'done']);
});
test('with after none, a commit runs without its push Tests', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file } = trunk(f, 2, { runs: [{ name: 'release', command: 'fake-release' }], after: 'none' });
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.pushRuns = {}; });
  assert.deepEqual(outcomes(sweepTick(f, file).stdout), [[commits[1], 'done', '']]);
});
test('a commit whose push Tests or test job did not succeed waits, reported as an error, until a rerun turns it green', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'failure' }; });
  const red = sweepTick(f, file);
  assert.equal(red.status, 1);
  assert.equal(red.stderr, `Example/app: post-merge: ${commits[1]} waits: Tests did not succeed on the commit\n`);
  edit(f, live => { live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'success', jobConclusion: 'failure' }; });
  assert.equal(sweepTick(f, file).stderr, `Example/app: post-merge: ${commits[1]} waits: Run test suite did not succeed on the commit\n`);
  assert.equal(existsSync(ledger(commits[1])), false, 'a wait records no attempt');
  edit(f, live => { live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'success' }; });
  assert.deepEqual(outcomes(sweepTick(f, file).stdout), [[commits[1], 'done', '']]);
});
const redNotice = (commit: string, reason: string, pr = '') => `-e display notification "Trunk red at ${commit.slice(0, 8)}: ${reason}${pr}" with title "Converge local" subtitle "Example/app" sound name "Basso"`;
test('a commit that waits on a red push run notifies once, recorded before the notification; a dry run notifies nothing', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, state } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'failure' }; live.commitPulls = { [commits[1]]: [merged(41)] }; });
  assert.equal(sweepTick(f, file, ['--dry-run']).status, 1);
  assert.deepEqual(f.notices(), []);
  assert.equal(existsSync(join(state, 'red-trunk')), false);
  const red = sweepTick(f, file);
  assert.equal(red.stderr, `Example/app: post-merge: ${commits[1]} waits: Tests did not succeed on the commit\n`, 'the notice adds no error line');
  assert.deepEqual(f.notices(), [redNotice(commits[1], 'Tests did not succeed on the commit', ' (PR #41)')]);
  const record = JSON.parse(readFileSync(redTrunkFile(state, 'Example/app', commits[1]), 'utf8'));
  assert.deepEqual([record.schemaVersion, record.repo, record.commit, record.pr, record.reason], [1, 'Example/app', commits[1], 41, 'Tests did not succeed on the commit']);
  edit(f, live => { live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'success', jobConclusion: 'failure' }; });
  assert.equal(sweepTick(f, file).status, 1);
  assert.equal(f.notices().length, 1, 'one notification per red commit, whatever the next tick reads');
});
test('a red-trunk notification that fails is an error once, and the record keeps the next tick from retrying it', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, state } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.pushRuns[commits[1]] = { status: 'completed', conclusion: 'failure' }; });
  writeFileSync(join(f.directory, 'osascript-exit'), '1');
  const red = sweepTick(f, file);
  assert.equal(red.stderr, `Example/app: post-merge: ${commits[1]} waits: Tests did not succeed on the commit\nExample/app: post-merge: ${commits[1]}: notification failed: osascript exited 1: fake osascript failed\n`);
  assert.equal(existsSync(redTrunkFile(state, 'Example/app', commits[1])), true);
  assert.equal(sweepTick(f, file).stderr, `Example/app: post-merge: ${commits[1]} waits: Tests did not succeed on the commit\n`);
  assert.equal(f.notices().length, 1);
});
test('without a postMerge block, the sweep tick notifies once for a red trunk tip, and not for a green or pending one', t => {
  const f = fixture(); t.after(f.cleanup);
  const checkout = f.checkout();
  const state = join(f.directory, 'state');
  const file = join(f.directory, 'converge-local.json');
  writeFileSync(file, JSON.stringify({ parent: 'claude', repos: [{ repo: 'Example/app', checkout }], pluginDir: f.directory, stateDirectory: state, sheetPath: join(f.directory, 'sheet.md'), logDirectory: f.directory }));
  const tip = f.state.trunk;
  const redTrunk = (stdout: string) => JSON.parse(stdout).repos[0].redTrunk;
  for (const run of [{ status: 'completed', conclusion: 'success' }, { status: 'in_progress', conclusion: null }]) {
    edit(f, live => { live.pushRuns = { [tip]: run }; });
    const quiet = sweepTick(f, file);
    assert.equal(quiet.status, 0, quiet.stderr);
    assert.deepEqual(redTrunk(quiet.stdout), { commit: tip, reason: null, errors: [] });
  }
  edit(f, live => { live.pushRuns = { [tip]: { status: 'completed', conclusion: 'cancelled' } }; });
  const dry = sweepTick(f, file, ['--dry-run']);
  assert.deepEqual([redTrunk(dry.stdout).reason, f.notices()], ['Tests did not succeed on the commit', []]);
  const red = sweepTick(f, file);
  assert.equal(red.status, 0, red.stderr);
  assert.deepEqual(redTrunk(red.stdout), { commit: tip, reason: 'Tests did not succeed on the commit', errors: [] });
  assert.equal(JSON.parse(red.stdout).repos[0].postMerge, null);
  assert.deepEqual(f.notices(), [redNotice(tip, 'Tests did not succeed on the commit')]);
  assert.equal(sweepTick(f, file).status, 0);
  assert.equal(f.notices().length, 1);
});
test('exit 75 defers the commit: the tip stays, the next tick tries again, and a 75 after 24 hours of deferring fails', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[2]; });
  writeFileSync(join(f.directory, 'exits', String(commits[1])), '75');
  const deferred = sweepTick(f, file);
  assert.equal(deferred.status, 0, deferred.stderr);
  assert.deepEqual([outcomes(deferred.stdout), pass(deferred.stdout).handled], [[[commits[1], 'deferred', 'release exited 75']], commits[0]]);
  assert.equal(git(join(f.directory, 'checkout'), ['worktree', 'list', '--porcelain']).match(/^worktree /gm)?.length, 1, 'a deferred attempt removes its worktree too');
  assert.equal(sweepTick(f, file).status, 0);
  assert.deepEqual(ledgerOf(ledger(commits[1])).attempts.map(a => [a.n, a.outcome]), [[1, 'deferred'], [2, 'deferred']]);
  const aged = ledgerOf(ledger(commits[1]));
  aged.firstAttemptAt = new Date(Date.now() - (POST_MERGE_DEFER_HOURS + 1) * 3_600_000).toISOString();
  writeFileSync(ledger(commits[1]), JSON.stringify(aged));
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1);
  assert.deepEqual(outcomes(failed.stdout), [[commits[1], 'failed', `release exited 75 for 24 hours since ${aged.firstAttemptAt}`]]);
});
for (const [exit, outcome] of [[75, 'deferred'], [1, 'failed']] satisfies [number, string][]) test(`commands checkpoint with Linear disabled after ${outcome === 'deferred' ? 'deferral' : 'failure'}, and enabling Linear preserves successful runs`, t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2, { runs: [{ name: 'release', command: 'fake-release' }, { name: 'finish', command: 'fake-finish' }], linear: false });
  const commitSha = String(commits[1]);
  edit(f, live => { live.trunk = commitSha; });
  writeFileSync(join(f.directory, 'fake-finish'), '#!/bin/sh\necho finish >> "$FAKE_DIR/finished.txt"\ncp "$FAKE_DIR/state/post-merge/Example-app/$PSTACK_COMMIT.json" "$FAKE_DIR/checkpoint-observed.json"\nif [ -f "$FAKE_DIR/finish-exit" ]; then exit "$(cat "$FAKE_DIR/finish-exit")"; fi\n');
  chmodSync(join(f.directory, 'fake-finish'), 0o700);
  writeFileSync(join(f.directory, 'finish-exit'), String(exit));
  const first = byHand(f, file, ['--repo', 'Example/app', '--commit', commitSha]);
  assert.equal(first.status, exit === 75 ? 0 : 1, first.stderr);
  assert.equal(JSON.parse(first.stdout).commits[0].outcome, outcome);
  const prior = ledgerOf(ledger(commitSha));
  assert.deepEqual(prior.checkpoint?.commands.map(r => [r.name, r.command]), [['release', 'fake-release']]);
  assert.deepEqual(ledgerOf(join(f.directory, 'checkpoint-observed.json')).checkpoint?.commands, prior.checkpoint?.commands);
  rmSync(join(f.directory, 'finish-exit'));
  edit(f, live => { const config = JSON.parse(live.blobs['.cursor/converge.json']); config.postMerge.linear = true; live.blobs['.cursor/converge.json'] = JSON.stringify(config); });
  const retried = byHand(f, file, ['--repo', 'Example/app', '--commit', commitSha]);
  assert.equal(retried.status, 0, retried.stderr);
  assert.equal(JSON.parse(retried.stdout).commits[0].outcome, 'done');
  const saved = ledgerOf(ledger(commitSha));
  assert.deepEqual(saved.attempts.map(a => a.outcome), [outcome, 'done']);
  assert.deepEqual(saved.checkpoint?.commands.map(r => r.name), ['release', 'finish']);
  assert.deepEqual(saved.checkpoint?.commands[0], prior.checkpoint?.commands[0]);
  assert.equal(released(f).length, 1);
  assert.equal(readFileSync(join(f.directory, 'finished.txt'), 'utf8'), 'finish\nfinish\n');
});
test('a failed commit stops the queue, comments once on its merged PR, notifies once, shows in status, repeats the error on every tick, and manual retry retains its ledger', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[2]; live.commitPulls = { [commits[1]]: [merged(41)] }; });
  writeFileSync(join(f.directory, 'exits', String(commits[1])), '1');
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1);
  const error = `Example/app: post-merge: ${commits[1]} failed: release exited 1; retry with converge-local post-merge --repo Example/app --commit ${commits[1]}, retaining the ledger`;
  assert.equal(failed.stderr, error + '\n');
  const logFile = ledgerOf(ledger(commits[1])).attempts[0]?.runs[0]?.logFile;
  assert.deepEqual(f.read().posted, [{ pr: 41, body: [`The local converge daemon's post-merge stopped on commit ${commits[1]}: release exited 1.`, '', 'Runs:', `- release exited 1 (${logFile})`, '', `Later trunk commits wait. Retry with \`converge-local post-merge --repo Example/app --commit ${commits[1]}\`, retaining the ledger.`].join('\n') }]);
  assert.deepEqual(f.notices(), [`-e display notification "Post-merge stopped on commit ${commits[1]?.slice(0, 8)}: release exited 1 (PR #41)" with title "Converge local" subtitle "Example/app" sound name "Basso"`]);
  assert.deepEqual(released(f).map(l => l[1]), [commits[1]], 'the later commit waits');
  const status = JSON.parse(f.run('converge-local', ['status', '--config', file], env(f)).stdout);
  assert.deepEqual(status.postMerge, [{ repo: 'Example/app', tip: commits[0], commits: [{ commit: commits[1], pr: 41, outcome: 'failed', reason: 'release exited 1', attempts: 1, file: ledger(commits[1]) }] }]);
  const again = sweepTick(f, file);
  assert.equal(again.stderr, error + '\n');
  assert.equal(f.read().posted.length, 1, 'one comment per recorded failure');
  assert.equal(f.notices().length, 1, 'one notification per recorded failure');
  assert.equal(released(f).length, 1, 'a failed commit never runs again on its own');
  rmSync(join(f.directory, 'exits', String(commits[1])));
  assert.equal(byHand(f, file, ['--repo', 'Example/app', '--commit', String(commits[1])]).status, 0);
  assert.equal(ledgerOf(ledger(commits[1])).attempts.length, 2);
  const retried = sweepTick(f, file);
  assert.equal(retried.status, 0, retried.stderr);
  assert.deepEqual(outcomes(retried.stdout).map((o: string[]) => o[1]), ['done', 'done']);
});
test('a failure comment that cannot be posted leaves the failure standing and names the comment', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.commitPulls = { [commits[1]]: [merged(41)] }; live.failPost = 'issues/41/comments'; });
  writeFileSync(join(f.directory, 'exits', String(commits[1])), '1');
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1);
  assert.equal(failed.stderr, `Example/app: post-merge: ${commits[1]} failed: release exited 1; retry with converge-local post-merge --repo Example/app --commit ${commits[1]}, retaining the ledger\nExample/app: post-merge: ${commits[1]}: failure comment failed: gh request failed\n`);
  assert.equal(ledgerOf(ledger(commits[1])).attempts[0]?.outcome, 'failed');
});
test('a notification that cannot be shown leaves the failure and its comment standing and names the notification', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; live.commitPulls = { [commits[1]]: [merged(41)] }; });
  writeFileSync(join(f.directory, 'exits', String(commits[1])), '1');
  writeFileSync(join(f.directory, 'osascript-exit'), '1');
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1);
  assert.equal(failed.stderr, `Example/app: post-merge: ${commits[1]} failed: release exited 1; retry with converge-local post-merge --repo Example/app --commit ${commits[1]}, retaining the ledger\nExample/app: post-merge: ${commits[1]}: notification failed: osascript exited 1: fake osascript failed\n`);
  assert.equal(ledgerOf(ledger(commits[1])).attempts[0]?.outcome, 'failed');
  assert.deepEqual(f.read().posted.map((comment: { pr: number }) => comment.pr), [41]);
});
test('a ledger that already ends done only advances the tip', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  const at = new Date().toISOString();
  writeJsonFile(ledger(String(commits[1])), { schemaVersion: 1, repo: 'Example/app', commit: commits[1], pr: null, firstAttemptAt: at, attempts: [{ n: 1, startedAt: at, endedAt: at, runs: [], outcome: 'done', reason: '', runDirectory: '/tmp/earlier' }] });
  edit(f, live => { live.trunk = commits[2]; });
  const result = sweepTick(f, file);
  assert.equal(result.status, 0, result.stderr);
  assert.deepEqual(outcomes(result.stdout), [[commits[1], 'done', 'done on an earlier pass'], [commits[2], 'done', '']]);
  assert.deepEqual(released(f).map(l => l[1]), [commits[2]]);
});
test('a tip that does not descend from the handled tip, more than 50 commits and a truncated compare fail the pass and store nothing', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, stateFile } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  const reset = `delete ${stateFile} to start again from the current tip`;
  const store = (tip: string) => writeFileSync(stateFile, JSON.stringify({ schemaVersion: 1, repo: 'Example/app', tip }));
  const gone = 'e'.repeat(40);
  store(gone); edit(f, live => { live.trunk = commits[1]; });
  const forced = sweepTick(f, file);
  assert.equal(forced.status, 1);
  assert.equal(forced.stderr, `Example/app: post-merge: trunk tip ${commits[1]} does not descend from the handled tip ${gone}; ${reset}\n`);
  const many = Array.from({ length: 52 }, (_, i) => String(i).padStart(40, '0'));
  store(String(many[0])); edit(f, live => { live.trunkHistory = many.map((sha, i) => ({ sha, parents: i ? [many[i - 1]] : [] })); live.trunk = many[51]; });
  assert.equal(sweepTick(f, file).stderr, `Example/app: post-merge: more than 50 trunk commits since the handled tip ${many[0]}; ${reset}\n`);
  edit(f, live => { live.trunk = many[5]; live.compareLimit = 2; });
  assert.equal(sweepTick(f, file).stderr, `Example/app: post-merge: the compare from ${many[0]} lists 2 of 5 commits; ${reset}\n`);
  assert.equal(JSON.parse(readFileSync(stateFile, 'utf8')).tip, many[0]);
  assert.deepEqual(released(f), []);
});
test('a state or ledger file that does not parse fails the pass with the file named, runs nothing and stores nothing', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, stateFile, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; });
  mkdirSync(join(ledger(String(commits[1])), '..'), { recursive: true }); writeFileSync(ledger(String(commits[1])), '{');
  const badLedger = sweepTick(f, file);
  assert.equal(badLedger.status, 1);
  assert.match(badLedger.stderr, new RegExp(`^Example/app: post-merge: Invalid post-merge ledger ${ledger(String(commits[1]))}: `));
  writeFileSync(stateFile, '{'); rmSync(ledger(String(commits[1])));
  const badState = sweepTick(f, file);
  assert.equal(badState.status, 1);
  assert.match(badState.stderr, new RegExp(`^Example/app: post-merge: Invalid post-merge state file ${stateFile}: `));
  assert.equal(readFileSync(stateFile, 'utf8'), '{', 'never re-anchored in silence');
  assert.deepEqual(released(f), []);
});
test('a command that does not start fails the attempt with exitCode null', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2, { runs: [{ name: 'release', command: 'no-such-command-anywhere' }] });
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; });
  const result = sweepTick(f, file);
  assert.equal(result.status, 1);
  assert.deepEqual(outcomes(result.stdout), [[commits[1], 'failed', 'release did not start']]);
  assert.equal(ledgerOf(ledger(String(commits[1]))).attempts[0]?.runs[0]?.exitCode, null);
  assert.deepEqual(f.notices(), [`-e display notification "Post-merge stopped on commit ${commits[1]?.slice(0, 8)}: release did not start" with title "Converge local" subtitle "Example/app" sound name "Basso"`], 'a direct push has no PR to name');
});
test('a command past its cap is killed and the attempt fails with reason timeout', async t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; });
  writeFileSync(join(f.directory, 'sleep'), '');
  const report = await inProcess(f, () => tickSweep(loadConfig(file), { dryRun: false, runCapMs: 300 }));
  assert.deepEqual(report.repos[0]?.postMerge?.commits.map(c => [c.outcome, c.reason]), [['failed', 'timeout']]);
  assert.equal(ledgerOf(ledger(String(commits[1]))).attempts[0]?.runs[0]?.exitCode, 143);
});
test('a commit the checkout cannot fetch is an error with no attempt, tried again on the next tick', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  const ghost = 'f'.repeat(40);
  edit(f, live => { live.trunkHistory.push({ sha: ghost, parents: [commits[1]] }); live.pushRuns[ghost] = { status: 'completed', conclusion: 'success' }; live.trunk = ghost; });
  const result = sweepTick(f, file);
  assert.equal(result.status, 1);
  assert.deepEqual(outcomes(result.stdout).map((o: string[]) => [o[0], o[1]]), [[commits[1], 'done'], [ghost, 'waiting']]);
  assert.match(result.stderr, new RegExp(`^Example/app: post-merge: ${ghost}: checkout failed: git fetch failed: `, 'm'));
  assert.equal(existsSync(ledger(ghost)), false);
  assert.equal(pass(result.stdout).handled, commits[1]);
});
test('a dry run prints what the pass would run and writes nothing', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, state, stateFile, ledger } = trunk(f, 3);
  const fresh = sweepTick(f, file, ['--dry-run']);
  assert.equal(fresh.status, 0, fresh.stderr);
  assert.deepEqual(pass(fresh.stdout), { tip: commits[0], handled: null, note: 'first pass: would store the trunk tip and run nothing', commits: [], errors: [] });
  assert.equal(existsSync(state), false);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[2]; });
  const dry = sweepTick(f, file, ['--dry-run']);
  assert.equal(dry.status, 0, dry.stderr);
  const [entry] = pass(dry.stdout).commits;
  assert.deepEqual([entry.commit, entry.outcome, entry.reason, entry.ledger], [commits[1], 'dry-run', 'release: fake-release', ledger(String(commits[1]))]);
  assert.match(entry.runDirectory, /\/converge-local\/post-merge\/Example-app-[0-9a-f]{8}-1-\d+$/);
  assert.equal(existsSync(entry.runDirectory), false);
  assert.equal(existsSync(join(state, 'post-merge', 'Example-app')), false);
  assert.equal(JSON.parse(readFileSync(stateFile, 'utf8')).tip, commits[0]);
  assert.deepEqual(released(f), []);
});
const byHand = (f: F, file: string, args: string[]) => f.run('converge-local', ['post-merge', ...args, '--config', file], env(f));
function manualLinear(f: F, count = 2) {
  const setup = trunk(f, count, { runs: [{ name: 'release', command: 'fake-release' }], linear: true });
  const commitSha = String(setup.commits[1]), remote = join(f.directory, 'linear-remote.json'), plan = join(f.directory, 'reviewed-plan.json');
  linearMergedPr(f, commitSha);
  edit(f, live => { live.trunk = commitSha; });
  const config = JSON.parse(readFileSync(setup.file, 'utf8'));
  config.pluginDir = fileURLToPath(new URL('../../../../../', import.meta.url));
  writeJsonFile(setup.file, config);
  writeFileSync(join(f.directory, 'sheet.md'), 'converge raiz: claude:fable@max\n');
  const cli = join(f.directory, 'claude');
  writeFileSync(cli, readFileSync(new URL('../fixtures/linear.mjs', import.meta.url), 'utf8').replace('const prompt =', "if (process.env.LINEAR_ARGV) writeFileSync(process.env.LINEAR_ARGV + '.calls', 'call\\n', { flag: 'a' });\nconst prompt =")); chmodSync(cli, 0o700);
  const state = {
    mode: 'normal',
    issue: { id: 'ENG-1', uuid: 'issue-uuid', url: issueUrl, description: 'Retain retry behavior. Production rollout remains pending.', statusType: 'started', documents: [], projectId: 'project-1' },
    project: { id: 'P-ENG-1', uuid: 'project-1', description: 'Historical project plan.', resources: [] },
    documents: [], comments: Array<{ id: string; body: string }>(), mutations: Array<Pick<LinearPlan['effects'][number], 'tool' | 'args'>>(),
  };
  writeJsonFile(remote, state);
  const linearEnv = { ...env(f), LINEAR_REMOTE: remote, LINEAR_ARGV: join(f.directory, 'linear-argv.json') };
  const run = (args: string[]) => f.run('converge-local', ['post-merge', '--repo', 'Example/app', '--commit', commitSha, '--config', setup.file, ...args], linearEnv);
  const sweep = () => f.run('converge-local', ['tick', '--job', 'sweep', '--config', setup.file], linearEnv);
  const sessions = () => existsSync(join(f.directory, 'linear-argv.json.calls')) ? readFileSync(join(f.directory, 'linear-argv.json.calls'), 'utf8').trim().split('\n').length : 0;
  return { ...setup, commitSha, remote, plan, run, sweep, sessions, read: (): typeof state => JSON.parse(readFileSync(remote, 'utf8')) };
}
test('public sweep settles progress, exposes withheld completion, and advances after owner rejection without reassessment', t => {
  const f = fixture(); t.after(f.cleanup);
  const s = manualLinear(f, 3), criterion = 'ENG-1 labels must include pstack.';
  const issue = { ...s.read().issue, description: criterion + '\nPersist the release checkpoint before the next command.', labels: ['pstack'] };
  const observed = { id: 'observed', tool: LINEAR_PREFIX + 'get_issue', args: {}, result: issue, error: false, line: 1, session: 'fixture' } satisfies NativeCall;
  const proof = proofCatalogue(merge(), [observed]).find(p => p.kind === 'structural' && p.field === 'labels'); assert.ok(proof);
  const assessment = { targets: [{ url: issueUrl, coverage: 'complete', references: [], obligations: [{ source: 'ENG-1', quote: criterion, kind: 'acceptance', requiredClass: 'structural', status: 'met', outcome: { subject: issueUrl, field: 'labels', operator: 'includes', value: 'pstack' }, proofIds: [proof.id], relevance: 'The required label is present.' }] }] };
  writeJsonFile(s.remote, { ...s.read(), issue, assessment });
  edit(f, live => { live.trunk = s.commits[0]; }); assert.equal(s.sweep().status, 0);
  edit(f, live => { live.trunk = s.commitSha; });
  const automatic = s.sweep(); assert.equal(automatic.status, 0, automatic.stderr);
  const pending = pass(automatic.stdout).commits[0]; assert.equal(pending.outcome, 'done');
  assert.match(pending.reason, /completion awaits owner review/);
  const artifact = pending.reason.match(/Concrete Linear plan (.+) \(([a-f0-9]{64})\)/); assert.ok(artifact);
  const reviewed = readFileSync(artifact[1], 'utf8'), approved = parseLinearPlan(JSON.parse(reviewed));
  assert.equal(approved.effects.length, 1); assert.equal(approved.effects[0].tool, LINEAR_PREFIX + 'save_issue'); assert.ok(artifact[1].startsWith(s.state));
  assert.equal(ledgerOf(s.ledger(s.commitSha)).checkpoint?.linear?.effects.find(e => e.kind === 'complete')?.status.kind, 'withheld');
  assert.equal(s.read().mutations.length, 1); assert.equal(s.read().mutations[0].tool, LINEAR_PREFIX + 'save_comment'); assert.equal(s.read().issue.statusType, 'started'); assert.equal(released(f).length, 1);
  assert.match(s.read().comments[0].body, /completion awaits owner review/);
  rmSync(pending.runDirectory, { recursive: true, force: true }); assert.equal(readFileSync(artifact[1], 'utf8'), reviewed);
  const aged = ledgerOf(s.ledger(s.commitSha)); aged.firstAttemptAt = new Date(Date.now() - 26 * 3_600_000).toISOString(); writeJsonFile(s.ledger(s.commitSha), aged);
  const declined = join(f.directory, 'declined-plan.json'); writeJsonFile(declined, createLinearPlan({ ...approved, effects: [] }));
  // The ledger settled before a crash could store the handled tip.
  writeJsonFile(s.stateFile, { schemaVersion: 1, repo: 'Example/app', tip: s.commits[0] });
  const beforeRejection = readFileSync(s.stateFile, 'utf8'), rejected = s.run(['--plan', declined]); assert.equal(rejected.status, 1); assert.match(rejected.stderr, /effects changed/);
  assert.equal(readFileSync(s.stateFile, 'utf8'), beforeRejection); assert.equal(s.read().mutations.length, 1); assert.deepEqual(ledgerOf(s.ledger(s.commitSha)).attempts.map(a => a.outcome), ['done', 'failed']);
  assert.match(rejected.stderr, /automatic processing is already complete/);
  const failure = f.read().comments.find((c: {body: string}) => c.body.includes('The manual post-merge replay')); assert.ok(failure); assert.match(failure.body, /Automatic processing is already complete; later trunk commits continue/); assert.ok(!failure.body.includes('Later trunk commits wait'));
  assert.match(f.notices()[0], /automatic processing is complete/);
  edit(f, live => { live.trunk = s.commits[2]; live.commitPulls[s.commits[2]] = []; });
  const nativeCalls = s.sessions(), next = s.sweep(); assert.equal(next.status, 0, next.stderr); assert.deepEqual(pass(next.stdout).commits.map((c: Handled) => [c.commit, c.outcome]), [[s.commitSha, 'done'], [s.commits[2], 'done']]); assert.equal(released(f).length, 2); assert.equal(s.sessions(), nativeCalls);
  const saved = readFileSync(s.ledger(s.commitSha), 'utf8'), repeat = s.sweep(); assert.equal(repeat.status, 0, repeat.stderr); assert.deepEqual(pass(repeat.stdout).commits, []); assert.equal(s.sessions(), nativeCalls); assert.equal(readFileSync(s.ledger(s.commitSha), 'utf8'), saved); assert.equal(s.read().mutations.length, 1);
  const status = f.run('converge-local', ['status', '--config', s.file], env(f)); assert.equal(status.status, 0, status.stderr);
  const visible = JSON.parse(status.stdout).postMerge[0].commits.find((c: {commit: string}) => c.commit === s.commitSha); assert.deepEqual(visible.pendingCompletion.targets, [issueUrl]); assert.equal(visible.pendingCompletion.processingComplete, true); assert.ok(visible.pendingCompletion.reason.includes(artifact[1])); assert.equal(s.sessions(), nativeCalls);
  const dry = s.run(['--dry-run', '--plan', artifact[1]]); assert.equal(dry.status, 0, dry.stderr); assert.equal(readFileSync(artifact[1], 'utf8'), reviewed);
  const applied = s.run(['--plan', artifact[1]]); assert.equal(applied.status, 0, applied.stderr); assert.equal(JSON.parse(applied.stdout).commits[0].outcome, 'done');
  assert.deepEqual(s.read().mutations.slice(1), approved.effects.map(({ tool, args }) => ({ tool, args }))); assert.equal(s.read().issue.statusType, 'completed'); assert.equal(readFileSync(artifact[1], 'utf8'), reviewed); assert.equal(released(f).length, 2);
  assert.deepEqual(ledgerOf(s.ledger(s.commitSha)).attempts.map(a => a.outcome), ['done', 'failed', 'done']);
});
test('manual CLI emits a concrete reviewed plan and applies exactly its effects without changing the artifact', t => {
  const f = fixture(); t.after(f.cleanup);
  const s = manualLinear(f);
  const dry = s.run(['--dry-run', '--plan', s.plan]);
  assert.equal(dry.status, 0, dry.stderr);
  const reviewed = readFileSync(s.plan, 'utf8'), plan = parseLinearPlan(JSON.parse(reviewed));
  assert.deepEqual(plan.merge, { repo: 'Example/app', pr: 1, head: f.state.head, commit: s.commitSha });
  assert.equal(plan.effects.length, 1);
  assert.equal(plan.effects[0].tool, 'mcp__claude_ai_Linear__save_comment');
  assert.equal(plan.effects[0].args.issueId, 'issue-uuid');
  assert.match(String(plan.effects[0].args.body), new RegExp(s.commitSha));
  assert.deepEqual([released(f), s.read().mutations, s.read().comments], [[], [], []]);
  assert.equal(existsSync(s.ledger(s.commitSha)), false);
  const apply = s.run(['--plan', s.plan]);
  assert.equal(apply.status, 0, apply.stderr);
  assert.equal(JSON.parse(apply.stdout).commits[0].outcome, 'done');
  assert.deepEqual(s.read().mutations, plan.effects.map(({ tool, args }) => ({ tool, args })));
  assert.equal(s.read().comments[0].body, plan.effects[0].args.body);
  assert.equal(s.read().issue.statusType, 'started');
  assert.equal(ledgerOf(s.ledger(s.commitSha)).checkpoint?.linear?.effects[0].status.kind, 'confirmed');
  assert.equal(released(f).length, 1);
  assert.equal(readFileSync(s.plan, 'utf8'), reviewed);
});
test('manual CLI refuses admitted Linear targets without a reviewed plan and records a visible failure', t => {
  const f = fixture(); t.after(f.cleanup);
  const s = manualLinear(f), result = s.run([]);
  assert.equal(result.status, 1);
  assert.match(result.stderr, /Manual Linear apply requires.*--plan/);
  assert.equal(JSON.parse(result.stdout).commits[0].outcome, 'failed');
  assert.equal(ledgerOf(s.ledger(s.commitSha)).attempts[0].outcome, 'failed');
  assert.deepEqual(s.read().mutations, []);
});
test('manual CLI refuses changed Linear sources, preserves the reviewed artifact, and recovers with a fresh plan', t => {
  const f = fixture(); t.after(f.cleanup);
  const s = manualLinear(f);
  const dry = s.run(['--dry-run', '--plan', s.plan]);
  assert.equal(dry.status, 0, dry.stderr);
  const reviewed = readFileSync(s.plan, 'utf8'), changed = s.read();
  changed.issue.description += ' New acceptance criterion.';
  writeJsonFile(s.remote, changed);
  const refused = s.run(['--plan', s.plan]);
  assert.equal(refused.status, 1);
  assert.match(refused.stderr, /Linear sources changed; generate and review a new plan/);
  assert.equal(JSON.parse(refused.stdout).commits[0].outcome, 'failed');
  assert.equal(ledgerOf(s.ledger(s.commitSha)).attempts[0].outcome, 'failed');
  assert.equal(readFileSync(s.plan, 'utf8'), reviewed);
  assert.deepEqual(s.read().mutations, []);
  const overwritten = s.run(['--dry-run', '--plan', s.plan]); assert.equal(overwritten.status, 1); assert.match(overwritten.stderr, /new --plan path/); assert.equal(readFileSync(s.plan, 'utf8'), reviewed);
  const newPlan = join(f.directory, 'new-reviewed-plan.json');
  const fresh = s.run(['--dry-run', '--plan', newPlan]);
  assert.equal(fresh.status, 0, fresh.stderr);
  const updated = readFileSync(newPlan, 'utf8');
  assert.notEqual(parseLinearPlan(JSON.parse(updated)).sourceDigest, parseLinearPlan(JSON.parse(reviewed)).sourceDigest);
  assert.equal(ledgerOf(s.ledger(s.commitSha)).attempts.length, 1);
  const applied = s.run(['--plan', newPlan]);
  assert.equal(applied.status, 0, applied.stderr);
  assert.deepEqual(ledgerOf(s.ledger(s.commitSha)).attempts.map(a => a.outcome), ['failed', 'done']);
  assert.equal(s.read().mutations.length, 1);
  assert.equal(released(f).length, 1, 'the successful repository command is not repeated after refusal');
  assert.equal(readFileSync(newPlan, 'utf8'), updated); assert.equal(readFileSync(s.plan, 'utf8'), reviewed);
});
for (const linear of [false, true]) test(`manual --plan leaves repository commands unchanged when Linear is ${linear ? 'enabled without targets' : 'disabled'}`, t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2, { runs: [{ name: 'release', command: 'fake-release' }], linear });
  const commitSha = String(commits[1]), plan = join(f.directory, 'reviewed-plan.json');
  edit(f, live => { live.trunk = commitSha; });
  const dry = byHand(f, file, ['--repo', 'Example/app', '--commit', commitSha, '--dry-run', '--plan', plan]);
  assert.equal(dry.status, 0, dry.stderr);
  assert.equal(JSON.parse(dry.stdout).commits[0].outcome, 'dry-run');
  assert.equal(existsSync(plan), false);
  assert.equal(existsSync(ledger(commitSha)), false);
  assert.equal(released(f).length, 0);
  const apply = byHand(f, file, ['--repo', 'Example/app', '--commit', commitSha, '--plan', plan]);
  assert.equal(apply.status, 0, apply.stderr);
  assert.equal(JSON.parse(apply.stdout).commits[0].outcome, 'done');
  assert.equal(existsSync(plan), false);
  assert.equal(released(f).length, 1);
});
test('post-merge runs one attempt by hand on a trunk commit, whatever its ledger says, and leaves the handled tip to the next tick', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, stateFile, ledger } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[2]; });
  writeFileSync(join(f.directory, 'exits', String(commits[1])), '1');
  assert.equal(sweepTick(f, file).status, 1);
  rmSync(join(f.directory, 'exits', String(commits[1])));
  const dry = byHand(f, file, ['--repo', 'Example/app', '--commit', String(commits[1]), '--dry-run']);
  assert.equal(dry.status, 0, dry.stderr);
  assert.equal(JSON.parse(dry.stdout).commits[0].outcome, 'dry-run');
  assert.equal(ledgerOf(ledger(String(commits[1]))).attempts.length, 1, 'a dry run records nothing');
  const manual = byHand(f, file, ['--repo', 'Example/app', '--commit', String(commits[1])]);
  assert.equal(manual.status, 0, manual.stderr);
  const printed = JSON.parse(manual.stdout);
  assert.deepEqual([printed.job, printed.repo, printed.handled, printed.commits.map((c: Handled) => c.outcome)], ['post-merge', 'Example/app', commits[0], ['done']]);
  assert.deepEqual(ledgerOf(ledger(String(commits[1]))).attempts.map(a => a.outcome), ['failed', 'done']);
  assert.equal(JSON.parse(readFileSync(stateFile, 'utf8')).tip, commits[0], 'the stored tip does not move by hand');
  const next = sweepTick(f, file);
  assert.equal(next.status, 0, next.stderr);
  assert.deepEqual(outcomes(next.stdout), [[commits[1], 'done', 'done on an earlier pass'], [commits[2], 'done', '']]);
});
test('post-merge refuses a repository outside the configuration, a commit trunk does not descend from, a short SHA and a contract without postMerge', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file } = trunk(f, 2);
  const refused = (args: string[], pattern: RegExp) => { const result = byHand(f, file, args); assert.equal(result.status, 1); assert.match(result.stderr, pattern); };
  refused(['--repo', 'Example/other', '--commit', String(commits[0])], /^Example\/other is not in the configuration /);
  refused(['--repo', 'Example/app', '--commit', 'e'.repeat(40)], new RegExp(`^${'e'.repeat(40)} is not a trunk commit: the tip ${commits[0]} does not descend from it`));
  refused(['--repo', 'Example/app', '--commit', 'abc123'], /^Expected full commit SHA/);
  refused(['--repo', 'Example/app'], /^Usage: converge-local /);
  edit(f, live => { const config = JSON.parse(live.blobs['.cursor/converge.json']); delete config.postMerge; live.blobs['.cursor/converge.json'] = JSON.stringify(config); });
  refused(['--repo', 'Example/app', '--commit', String(commits[0])], /^Example\/app has no postMerge block in its trunk contract/);
});
test('while another holder runs a repository\'s pass, the tick skips it and post-merge refuses', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, state } = trunk(f, 2);
  assert.equal(sweepTick(f, file).status, 0);
  edit(f, live => { live.trunk = commits[1]; });
  takeLease(postMergeLeaseFile(state, 'Example/app'), { by: 'post-merge:1', ttlHours: 1, pid: process.pid });
  const tick = sweepTick(f, file);
  assert.equal(tick.status, 0, tick.stderr);
  assert.match(pass(tick.stdout).note, /^post-merge of Example\/app is leased by post-merge:1 until /);
  const manual = byHand(f, file, ['--repo', 'Example/app', '--commit', String(commits[1])]);
  assert.equal(manual.status, 1);
  assert.match(manual.stderr, /^post-merge of Example\/app is leased by post-merge:1 until /);
  assert.deepEqual(released(f), []);
});
test('a trunk contract without the block forgets the handled tip, so a block added back starts with a first pass instead of a replay', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, stateFile } = trunk(f, 3);
  assert.equal(sweepTick(f, file).status, 0);
  const block = (on: boolean) => edit(f, live => { const config = JSON.parse(live.blobs['.cursor/converge.json']); if (on) config.postMerge = { runs: [{ name: 'release', command: 'fake-release' }] }; else delete config.postMerge; live.blobs['.cursor/converge.json'] = JSON.stringify(config); });
  block(false); edit(f, live => { live.trunk = commits[1]; });
  const dry = sweepTick(f, file, ['--dry-run']);
  assert.equal(pass(dry.stdout), null);
  assert.equal(existsSync(stateFile), true, 'a dry run forgets nothing');
  const without = sweepTick(f, file);
  assert.equal(without.status, 0, without.stderr);
  assert.equal(pass(without.stdout), null);
  assert.equal(existsSync(stateFile), false);
  block(true); edit(f, live => { live.trunk = commits[2]; });
  const back = sweepTick(f, file);
  assert.equal(back.status, 0, back.stderr);
  assert.deepEqual([pass(back.stdout).note, pass(back.stdout).commits, pass(back.stdout).handled], ['first pass: stored the trunk tip and ran nothing', [], commits[2]]);
  assert.deepEqual(released(f), []);
});
test('a successful local command checkpoints before native Linear unavailability and survives retries and opt-in changes', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2, { runs: [{ name: 'release', command: 'fake-release' }], linear: true });
  assert.equal(sweepTick(f, file).status, 0);
  const commitSha = String(commits[1]);
  linearMergedPr(f, commitSha);
  edit(f, live => { live.trunk = commitSha; });
  writeFileSync(join(f.directory, 'sheet.md'), 'converge raiz: claude:fable@max\n');
  const cli = join(f.directory, 'claude'), remote = join(f.directory, 'linear-remote.json');
  writeFileSync(cli, readFileSync(new URL('../fixtures/linear.mjs', import.meta.url))); chmodSync(cli, 0o700);
  writeJsonFile(remote, { mode: 'no-mcp', issue: { id: 'ENG-1' } });
  const sweep = () => f.run('converge-local', ['tick', '--job', 'sweep', '--config', file], { ...env(f), LINEAR_REMOTE: remote, LINEAR_ARGV: join(f.directory, 'linear-argv.json') });
  const run = () => f.run('converge-local', ['post-merge', '--config', file, '--repo', 'Example/app', '--commit', commitSha], { ...env(f), LINEAR_REMOTE: remote, LINEAR_ARGV: join(f.directory, 'linear-argv.json') });
  for (let n = 0; n < 2; n++) { const result = sweep(); assert.equal(result.status, 0, result.stderr); assert.equal(pass(result.stdout).commits[0].outcome, 'deferred', result.stdout); }
  const saved = ledgerOf(ledger(commitSha)); assert.equal(saved.checkpoint?.commands.length, 1); assert.equal(saved.attempts.length, 2);
  assert.equal(released(f).length, 1); assert.deepEqual(saved.attempts[1].runs.map(r => [r.name, r.exitCode]), [['release', 0], ['linear', 75]]);
  assert.ok(saved.checkpoint);
  saved.checkpoint.linear = { repo: 'Example/app', commit: commitSha, head: f.state.head, effects: [{ key: 'prior-comment', target: linearTarget(issueUrl), kind: 'comment', tool: 'mcp__claude_ai_Linear__save_comment', args: { issueId: 'ENG-1', body: 'prior reconciliation' }, marker: '<!-- prior reconciliation -->', status: { kind: 'sent' } }], logPaths: ['prior-native.jsonl'] };
  writeJsonFile(ledger(commitSha), saved);
  edit(f, live => { const config = JSON.parse(live.blobs['.cursor/converge.json']); config.postMerge.linear = false; live.blobs['.cursor/converge.json'] = JSON.stringify(config); });
  const optedOut = run(); assert.equal(optedOut.status, 0, optedOut.stderr);
  assert.equal(JSON.parse(optedOut.stdout).commits[0].outcome, 'done');
  const retained = ledgerOf(ledger(commitSha));
  assert.deepEqual(retained.checkpoint, saved.checkpoint);
  assert.deepEqual(retained.attempts.slice(0, 2), saved.attempts);
  assert.equal(released(f).length, 1);
  edit(f, live => { const config = JSON.parse(live.blobs['.cursor/converge.json']); config.postMerge.linear = true; live.blobs['.cursor/converge.json'] = JSON.stringify(config); });
  const enabled = sweep(); assert.equal(enabled.status, 0, enabled.stderr);
  assert.deepEqual([pass(enabled.stdout).commits[0].outcome, pass(enabled.stdout).commits[0].reason], ['done', 'done on an earlier pass']);
  assert.deepEqual(ledgerOf(ledger(commitSha)).checkpoint, saved.checkpoint);
  assert.equal(ledgerOf(ledger(commitSha)).attempts.length, 3);
  assert.equal(released(f).length, 1);
});
test('a permanent Linear admission refusal fails visibly and stops later trunk commits', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 3, { runs: [{ name: 'release', command: 'fake-release' }], linear: true });
  assert.equal(sweepTick(f, file).status, 0);
  const commitSha = String(commits[1]);
  linearMergedPr(f, commitSha, 'change\n\nPstack-Linear: ENG-1');
  edit(f, live => { live.trunk = commits[2]; });
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1, failed.stdout);
  assert.deepEqual(outcomes(failed.stdout), [[commitSha, 'failed', 'linear: Invalid URL']]);
  assert.equal(pass(failed.stdout).handled, commits[0]);
  const saved = ledgerOf(ledger(commitSha));
  assert.deepEqual(saved.attempts[0]?.runs.map(r => [r.name, r.exitCode]), [['release', 0], ['linear', 1]]);
  assert.equal(saved.attempts[0]?.outcome, 'failed');
  assert.match(failed.stderr, /failed: linear: Invalid URL; retry with converge-local post-merge/);
  assert.match(f.read().comments.at(-1).body, /post-merge stopped.*linear: Invalid URL/);
  assert.equal(f.notices().length, 1);
  const status = JSON.parse(f.run('converge-local', ['status', '--config', file], env(f)).stdout);
  assert.deepEqual(status.postMerge[0].commits.map((c: Handled) => [c.commit, c.outcome, c.reason]), [[commitSha, 'failed', 'linear: Invalid URL']]);
  const again = sweepTick(f, file);
  assert.equal(again.status, 1);
  assert.deepEqual(outcomes(again.stdout), [[commitSha, 'failed', 'linear: Invalid URL']]);
  assert.equal(released(f).length, 1);
  assert.equal(ledgerOf(ledger(commitSha)).attempts.length, 1);
  assert.equal(f.read().comments.length, 2);
  assert.equal(f.notices().length, 1);
});
test('transient Linear admission failures defer without repeating commands and fail after 24 hours', t => {
  const f = fixture(); t.after(f.cleanup);
  const { commits, file, ledger } = trunk(f, 2, { runs: [{ name: 'release', command: 'fake-release' }], linear: true });
  assert.equal(sweepTick(f, file).status, 0);
  const commitSha = String(commits[1]);
  linearMergedPr(f, commitSha);
  edit(f, live => { live.trunk = commitSha; live.failEndpoint = 'pulls/1/commits'; });
  const reason = 'linear: Linear admission or runtime unavailable: gh request failed';
  for (let n = 0; n < 2; n++) {
    const deferred = sweepTick(f, file);
    assert.equal(deferred.status, 0, deferred.stderr);
    assert.deepEqual(outcomes(deferred.stdout), [[commitSha, 'deferred', reason]]);
    assert.equal(pass(deferred.stdout).handled, commits[0]);
  }
  assert.equal(released(f).length, 1);
  const aged = ledgerOf(ledger(commitSha));
  aged.firstAttemptAt = new Date(Date.now() - (POST_MERGE_DEFER_HOURS + 1) * 3_600_000).toISOString();
  writeJsonFile(ledger(commitSha), aged);
  const failed = sweepTick(f, file);
  assert.equal(failed.status, 1);
  assert.deepEqual(outcomes(failed.stdout), [[commitSha, 'failed', `${reason} for 24 hours since ${aged.firstAttemptAt}`]]);
  assert.equal(released(f).length, 1);
});
